### PR TITLE
Typo Correction & Postman Collection/Environment

### PR DESCRIPTION
**Pull request by Julian88Tex**
Changes:
- typo corrections in documentation
- Created first draft of Postman Collection
- Created first draft of Postman Environment without an API key

Resources:
- Postman Workspace: https://www.postman.com/julian88tex/workspace/one-degree

### CODE REVIEW

**Comment by AngelAlvarado** [comment]
Thanks for your work on this. Please squash all your commits into one and include a description of all the changes of it.

**Comment by Julian88Tex** [comment]
@AngelAlvarado my pleasure. I've included descriptions in the changes for this PR. Let me know if you would like anymore details. For squashing, this can be done with merge:

Screen Shot 2021-04-16 at 9 53 17 AM

**Comment by AngelAlvarado** [comment]
@Julian88Tex yes we can do the merge commit automatically and it will be great to have a well-described commit instead, i.e. you can squash into one commit message with what you included in the description of this PR.

```
Changes:

    typo corrections in documentation
    Created first draft of Postman Collection
    Created first draft of Postman Environment without an API key

Resources:

    Postman Workspace: https://www.postman.com/julian88tex/workspace/one-degree
```

**Comment by Julian88Tex** [comment]
@AngelAlvarado Sure I can do this. Do you know of any documentation on how to squash previous commits? I've never done this before.

**Comment by AngelAlvarado** [comment]
Thanks @Julian88Tex , I'll take care of the rebasing. FYI it's as simple as `git rebase -i origin/master` then you squash or fixup the commits into 1.

**Comment by Julian88Tex** [comment]
@AngelAlvarado Great thanks for that and the merge!

**Pull request merged**
